"""empty message

Revision ID: 196745b8bfc6
Revises: 850005604eb0
Create Date: 2023-10-21 20:48:19.395915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '196745b8bfc6'
down_revision = '850005604eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d1_morning', sa.String(length=128), nullable=True),
    sa.Column('d1_afternoon', sa.String(length=128), nullable=True),
    sa.Column('d1_evening', sa.String(length=128), nullable=True),
    sa.Column('d2_morning', sa.String(length=128), nullable=True),
    sa.Column('d2_afternoon', sa.String(length=128), nullable=True),
    sa.Column('d2_evening', sa.String(length=128), nullable=True),
    sa.Column('d3_morning', sa.String(length=128), nullable=True),
    sa.Column('d3_afternoon', sa.String(length=128), nullable=True),
    sa.Column('d3_evening', sa.String(length=128), nullable=True),
    sa.Column('d4_morning', sa.String(length=128), nullable=True),
    sa.Column('d4_afternoon', sa.String(length=128), nullable=True),
    sa.Column('d4_evening', sa.String(length=128), nullable=True),
    sa.Column('d5_morning', sa.String(length=128), nullable=True),
    sa.Column('d5_afternoon', sa.String(length=128), nullable=True),
    sa.Column('d5_evening', sa.String(length=128), nullable=True),
    sa.Column('d6_morning', sa.String(length=128), nullable=True),
    sa.Column('d6_afternoon', sa.String(length=128), nullable=True),
    sa.Column('d6_evening', sa.String(length=128), nullable=True),
    sa.Column('d7_morning', sa.String(length=128), nullable=True),
    sa.Column('d7_afternoon', sa.String(length=128), nullable=True),
    sa.Column('d7_evening', sa.String(length=128), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('week',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('week',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    op.drop_table('history')
    # ### end Alembic commands ###
