"""empty message

Revision ID: 619c1ee9a7cb
Revises: 2c9f3ca31c8c
Create Date: 2024-05-18 19:47:08.451479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619c1ee9a7cb'
down_revision = '2c9f3ca31c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resign', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('is_resign')

    # ### end Alembic commands ###
