"""empty message

Revision ID: 9933b9649365
Revises: 34ad7879ce60
Create Date: 2023-11-02 10:47:09.340142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9933b9649365'
down_revision = '34ad7879ce60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_flow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('d1_morning', sa.Integer(), nullable=True),
    sa.Column('d1_afternoon', sa.Integer(), nullable=True),
    sa.Column('d1_evening', sa.Integer(), nullable=True),
    sa.Column('d2_morning', sa.Integer(), nullable=True),
    sa.Column('d2_afternoon', sa.Integer(), nullable=True),
    sa.Column('d2_evening', sa.Integer(), nullable=True),
    sa.Column('d3_morning', sa.Integer(), nullable=True),
    sa.Column('d3_afternoon', sa.Integer(), nullable=True),
    sa.Column('d3_evening', sa.Integer(), nullable=True),
    sa.Column('d4_morning', sa.Integer(), nullable=True),
    sa.Column('d4_afternoon', sa.Integer(), nullable=True),
    sa.Column('d4_evening', sa.Integer(), nullable=True),
    sa.Column('d5_morning', sa.Integer(), nullable=True),
    sa.Column('d5_afternoon', sa.Integer(), nullable=True),
    sa.Column('d5_evening', sa.Integer(), nullable=True),
    sa.Column('d6_morning', sa.Integer(), nullable=True),
    sa.Column('d6_afternoon', sa.Integer(), nullable=True),
    sa.Column('d6_evening', sa.Integer(), nullable=True),
    sa.Column('d7_morning', sa.Integer(), nullable=True),
    sa.Column('d7_afternoon', sa.Integer(), nullable=True),
    sa.Column('d7_evening', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_flow')
    # ### end Alembic commands ###
