"""empty message

Revision ID: ab6a247745cd
Revises: 9933b9649365
Create Date: 2024-03-05 15:51:21.035483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6a247745cd'
down_revision = '9933b9649365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('staff_name', sa.String(length=128), nullable=False),
    sa.Column('request', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_request')
    # ### end Alembic commands ###
